Algoritmo "SEQUENCIA_IMPARES"
//  
//  

Var
 x,b : inteiro
 i : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    //b<-1
    escreva("Digite um número: ")
    leia(x)
      //escreva(b)

      para i de 0 até x faca
       se i%2 <>0 então
       escreva(i)
       fimse
      fimpara

     //numeros entre b1 e b2

     // escreval("A soma dos números impares entre ",a1," e ",a2, " é ",soma)
Fimalgoritmo